language: r
cache: packages
latex: false

r_packages:
  - covr
  
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false

# This is the minimal set of R packages needed to run "R CMD check" on
# the package.
install:
  - R -e 'install.packages(c("testthat","devtools","knitr","rmarkdown","ggplot2","reshape2","softImpute"))'
  - R -e 'devtools::install_github("stephens999/ashr")'
  - R -e 'devtools::install_github("stephenslab/ebnm")'
  
after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
    - master
